export const allPost : any  = [
  {
    id : 1,
    img : 'src/image/mountains.jpg',
    latitude : 37.28,
    longitude : 49.6,
    title : 'Masal',
    username : 'Hossein Pourghadiri',
    description : 'Best Mountains and View In World',
  },
  {
    id : 2,
    img : 'src/image/mountains.jpg',
    latitude : 37.29,
    longitude : 49.59,
    title : 'Alpe',
    username : 'Ali Salari',
    description : 'Best Mountains and View In World',
  },
  {
    id : 3,
    img : 'src/image/mountains.jpg',
    latitude : 37.3,
    longitude : 49.4,
    title : 'Khalhkal',
    username : 'Majid Etemadi',
    description : 'Best Mountains and View In World',
  },
  {
    id : 4,
    img : 'src/image/mountains.jpg',
    latitude : 37.3,
    longitude : 49.61,
    title : 'Deylaman',
    username : 'Akbar Heydari',
    description : 'Best Mountains and View In World',
  },
]
